{{ if .Values.ingressController.awsRegion }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kube-ingress-aws-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kube-ingress-aws-controller.name" . }}
    chart: {{ template "kube-ingress-aws-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: ingress
spec:
  replicas: {{ .Values.ingressController.replicas }}
  selector:
    matchLabels:
      app: {{ template "kube-ingress-aws-controller.name" . }}
      chart: {{ template "kube-ingress-aws-controller.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: ingress
  template:
    metadata:
{{ if .Values.kube2iam.awsArn }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.kube2iam.awsArn }}
{{ end }}
      labels:
        app: {{ template "kube-ingress-aws-controller.name" . }}
        chart: {{ template "kube-ingress-aws-controller.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: ingress
    spec:
{{ if .Values.rbac.create }}
      serviceAccountName: {{ .Values.rbac.svcAccountName }}
{{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.ingressController.image.repository }}:{{ .Values.ingressController.image.tag }}"
        imagePullPolicy: {{ .Values.ingressController.image.pullPolicy }}
        env:
        - name: AWS_REGION
          value: {{ .Values.ingressController.awsRegion }}
{{- if or .Values.ingressController.args .Values.prometheusOperator.create }}
        args:
{{- end }}
{{- if .Values.prometheusOperator.create }}
          - "--metrics-address=:{{- .Values.ingressController.metricsEndpoint.port }}"
{{- end }}
{{- if .Values.ingressController.args }}
{{- range .Values.ingressController.args }}
          - {{ . | quote }}
{{- end }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.prometheusOperator.create }}
        ports:
        - name: {{ .Values.ingressController.metricsEndpoint.name }}
          containerPort: {{ .Values.ingressController.metricsEndpoint.port }}
{{- end }}
{{ end }}